// The shipped Flags of the World country dataset (SPEC §6). Sourced from
// the 193 UN member states + Vatican City + State of Palestine — the
// standard "flags of the world" quiz set. Every entry here must have a
// matching `public/flags/<code>.svg` file (verified by dataset.test.js), which
// is why the UI shows `COUNTRIES.length` (currently 195) rather than
// assuming a fixed number (SPEC §6).
//
// patternTag is a dominant-visual-structure heuristic (nordic-cross,
// star-and-crescent, pan-african, pan-arab, horizontal-tricolor,
// vertical-tricolor, complex-emblem, single-color-block, saltire, cross,
// bicolor, striped, other) used only for tier-3 distractor selection
// ("flags sharing colors/layout features", SPEC §9) — an approximation in
// service of gameplay, not a claim of vexillological precision.
export const DATASET_VERSION = 1

export const COUNTRIES = [
  { code: 'dz', name: 'Algeria', region: 'Africa', capital: 'Algiers', patternTag: 'star-and-crescent' },
  { code: 'ao', name: 'Angola', region: 'Africa', capital: 'Luanda', patternTag: 'pan-african' },
  { code: 'bj', name: 'Benin', region: 'Africa', capital: 'Porto-Novo', patternTag: 'pan-african' },
  { code: 'bw', name: 'Botswana', region: 'Africa', capital: 'Gaborone', patternTag: 'other' },
  { code: 'bf', name: 'Burkina Faso', region: 'Africa', capital: 'Ouagadougou', patternTag: 'pan-african' },
  { code: 'bi', name: 'Burundi', region: 'Africa', capital: 'Gitega', patternTag: 'pan-african' },
  { code: 'cv', name: 'Cabo Verde', region: 'Africa', capital: 'Praia', patternTag: 'pan-african' },
  { code: 'cm', name: 'Cameroon', region: 'Africa', capital: 'Yaounde', patternTag: 'pan-african' },
  { code: 'cf', name: 'Central African Republic', region: 'Africa', capital: 'Bangui', patternTag: 'other' },
  { code: 'td', name: 'Chad', region: 'Africa', capital: 'N\'Djamena', patternTag: 'vertical-tricolor' },
  { code: 'km', name: 'Comoros', region: 'Africa', capital: 'Moroni', patternTag: 'star-and-crescent' },
  { code: 'cg', name: 'Republic of the Congo', region: 'Africa', capital: 'Brazzaville', patternTag: 'pan-african' },
  { code: 'cd', name: 'DR Congo', region: 'Africa', capital: 'Kinshasa', patternTag: 'vertical-tricolor' },
  { code: 'ci', name: 'Cote d\'Ivoire', region: 'Africa', capital: 'Yamoussoukro', patternTag: 'vertical-tricolor' },
  { code: 'dj', name: 'Djibouti', region: 'Africa', capital: 'Djibouti', patternTag: 'other' },
  { code: 'eg', name: 'Egypt', region: 'Africa', capital: 'Cairo', patternTag: 'pan-arab' },
  { code: 'gq', name: 'Equatorial Guinea', region: 'Africa', capital: 'Malabo', patternTag: 'other' },
  { code: 'er', name: 'Eritrea', region: 'Africa', capital: 'Asmara', patternTag: 'other' },
  { code: 'sz', name: 'Eswatini', region: 'Africa', capital: 'Mbabane', patternTag: 'other' },
  { code: 'et', name: 'Ethiopia', region: 'Africa', capital: 'Addis Ababa', patternTag: 'pan-african' },
  { code: 'ga', name: 'Gabon', region: 'Africa', capital: 'Libreville', patternTag: 'vertical-tricolor' },
  { code: 'gm', name: 'Gambia', region: 'Africa', capital: 'Banjul', patternTag: 'pan-african' },
  { code: 'gh', name: 'Ghana', region: 'Africa', capital: 'Accra', patternTag: 'pan-african' },
  { code: 'gn', name: 'Guinea', region: 'Africa', capital: 'Conakry', patternTag: 'pan-african' },
  { code: 'gw', name: 'Guinea-Bissau', region: 'Africa', capital: 'Bissau', patternTag: 'pan-african' },
  { code: 'ke', name: 'Kenya', region: 'Africa', capital: 'Nairobi', patternTag: 'pan-african' },
  { code: 'ls', name: 'Lesotho', region: 'Africa', capital: 'Maseru', patternTag: 'other' },
  { code: 'lr', name: 'Liberia', region: 'Africa', capital: 'Monrovia', patternTag: 'other' },
  { code: 'ly', name: 'Libya', region: 'Africa', capital: 'Tripoli', patternTag: 'star-and-crescent' },
  { code: 'mg', name: 'Madagascar', region: 'Africa', capital: 'Antananarivo', patternTag: 'other' },
  { code: 'mw', name: 'Malawi', region: 'Africa', capital: 'Lilongwe', patternTag: 'pan-african' },
  { code: 'ml', name: 'Mali', region: 'Africa', capital: 'Bamako', patternTag: 'pan-african' },
  { code: 'mr', name: 'Mauritania', region: 'Africa', capital: 'Nouakchott', patternTag: 'star-and-crescent' },
  { code: 'mu', name: 'Mauritius', region: 'Africa', capital: 'Port Louis', patternTag: 'other' },
  { code: 'ma', name: 'Morocco', region: 'Africa', capital: 'Rabat', patternTag: 'other' },
  { code: 'mz', name: 'Mozambique', region: 'Africa', capital: 'Maputo', patternTag: 'pan-african' },
  { code: 'na', name: 'Namibia', region: 'Africa', capital: 'Windhoek', patternTag: 'pan-african' },
  { code: 'ne', name: 'Niger', region: 'Africa', capital: 'Niamey', patternTag: 'vertical-tricolor' },
  { code: 'ng', name: 'Nigeria', region: 'Africa', capital: 'Abuja', patternTag: 'vertical-tricolor' },
  { code: 'rw', name: 'Rwanda', region: 'Africa', capital: 'Kigali', patternTag: 'other' },
  { code: 'st', name: 'Sao Tome and Principe', region: 'Africa', capital: 'Sao Tome', patternTag: 'pan-african' },
  { code: 'sn', name: 'Senegal', region: 'Africa', capital: 'Dakar', patternTag: 'pan-african' },
  { code: 'sc', name: 'Seychelles', region: 'Africa', capital: 'Victoria', patternTag: 'other' },
  { code: 'sl', name: 'Sierra Leone', region: 'Africa', capital: 'Freetown', patternTag: 'pan-african' },
  { code: 'so', name: 'Somalia', region: 'Africa', capital: 'Mogadishu', patternTag: 'single-color-block' },
  { code: 'za', name: 'South Africa', region: 'Africa', capital: 'Pretoria', patternTag: 'other' },
  { code: 'ss', name: 'South Sudan', region: 'Africa', capital: 'Juba', patternTag: 'pan-arab' },
  { code: 'sd', name: 'Sudan', region: 'Africa', capital: 'Khartoum', patternTag: 'pan-arab' },
  { code: 'tz', name: 'Tanzania', region: 'Africa', capital: 'Dodoma', patternTag: 'other' },
  { code: 'tg', name: 'Togo', region: 'Africa', capital: 'Lome', patternTag: 'pan-african' },
  { code: 'tn', name: 'Tunisia', region: 'Africa', capital: 'Tunis', patternTag: 'star-and-crescent' },
  { code: 'ug', name: 'Uganda', region: 'Africa', capital: 'Kampala', patternTag: 'pan-african' },
  { code: 'zm', name: 'Zambia', region: 'Africa', capital: 'Lusaka', patternTag: 'pan-african' },
  { code: 'zw', name: 'Zimbabwe', region: 'Africa', capital: 'Harare', patternTag: 'pan-african' },
  { code: 'af', name: 'Afghanistan', region: 'Asia', capital: 'Kabul', patternTag: 'complex-emblem' },
  { code: 'am', name: 'Armenia', region: 'Asia', capital: 'Yerevan', patternTag: 'horizontal-tricolor' },
  { code: 'az', name: 'Azerbaijan', region: 'Asia', capital: 'Baku', patternTag: 'star-and-crescent' },
  { code: 'bh', name: 'Bahrain', region: 'Asia', capital: 'Manama', patternTag: 'striped' },
  { code: 'bd', name: 'Bangladesh', region: 'Asia', capital: 'Dhaka', patternTag: 'single-color-block' },
  { code: 'bt', name: 'Bhutan', region: 'Asia', capital: 'Thimphu', patternTag: 'complex-emblem' },
  { code: 'bn', name: 'Brunei', region: 'Asia', capital: 'Bandar Seri Begawan', patternTag: 'complex-emblem' },
  { code: 'kh', name: 'Cambodia', region: 'Asia', capital: 'Phnom Penh', patternTag: 'complex-emblem' },
  { code: 'cn', name: 'China', region: 'Asia', capital: 'Beijing', patternTag: 'other' },
  { code: 'cy', name: 'Cyprus', region: 'Asia', capital: 'Nicosia', patternTag: 'single-color-block' },
  { code: 'ge', name: 'Georgia', region: 'Asia', capital: 'Tbilisi', patternTag: 'cross' },
  { code: 'in', name: 'India', region: 'Asia', capital: 'New Delhi', patternTag: 'horizontal-tricolor' },
  { code: 'id', name: 'Indonesia', region: 'Asia', capital: 'Jakarta', patternTag: 'bicolor' },
  { code: 'ir', name: 'Iran', region: 'Asia', capital: 'Tehran', patternTag: 'other' },
  { code: 'iq', name: 'Iraq', region: 'Asia', capital: 'Baghdad', patternTag: 'pan-arab' },
  { code: 'il', name: 'Israel', region: 'Asia', capital: 'Jerusalem', patternTag: 'striped' },
  { code: 'jp', name: 'Japan', region: 'Asia', capital: 'Tokyo', patternTag: 'single-color-block' },
  { code: 'jo', name: 'Jordan', region: 'Asia', capital: 'Amman', patternTag: 'pan-arab' },
  { code: 'kz', name: 'Kazakhstan', region: 'Asia', capital: 'Astana', patternTag: 'complex-emblem' },
  { code: 'kw', name: 'Kuwait', region: 'Asia', capital: 'Kuwait City', patternTag: 'pan-arab' },
  { code: 'kg', name: 'Kyrgyzstan', region: 'Asia', capital: 'Bishkek', patternTag: 'complex-emblem' },
  { code: 'la', name: 'Laos', region: 'Asia', capital: 'Vientiane', patternTag: 'horizontal-tricolor' },
  { code: 'lb', name: 'Lebanon', region: 'Asia', capital: 'Beirut', patternTag: 'horizontal-tricolor' },
  { code: 'my', name: 'Malaysia', region: 'Asia', capital: 'Kuala Lumpur', patternTag: 'star-and-crescent' },
  { code: 'mv', name: 'Maldives', region: 'Asia', capital: 'Male', patternTag: 'single-color-block' },
  { code: 'mn', name: 'Mongolia', region: 'Asia', capital: 'Ulaanbaatar', patternTag: 'complex-emblem' },
  { code: 'mm', name: 'Myanmar', region: 'Asia', capital: 'Naypyidaw', patternTag: 'single-color-block' },
  { code: 'np', name: 'Nepal', region: 'Asia', capital: 'Kathmandu', patternTag: 'other' },
  { code: 'kp', name: 'North Korea', region: 'Asia', capital: 'Pyongyang', patternTag: 'single-color-block' },
  { code: 'om', name: 'Oman', region: 'Asia', capital: 'Muscat', patternTag: 'complex-emblem' },
  { code: 'pk', name: 'Pakistan', region: 'Asia', capital: 'Islamabad', patternTag: 'star-and-crescent' },
  { code: 'ps', name: 'Palestine', region: 'Asia', capital: 'Ramallah', patternTag: 'pan-arab' },
  { code: 'ph', name: 'Philippines', region: 'Asia', capital: 'Manila', patternTag: 'horizontal-tricolor' },
  { code: 'qa', name: 'Qatar', region: 'Asia', capital: 'Doha', patternTag: 'single-color-block' },
  { code: 'sa', name: 'Saudi Arabia', region: 'Asia', capital: 'Riyadh', patternTag: 'single-color-block' },
  { code: 'sg', name: 'Singapore', region: 'Asia', capital: 'Singapore', patternTag: 'star-and-crescent' },
  { code: 'kr', name: 'South Korea', region: 'Asia', capital: 'Seoul', patternTag: 'complex-emblem' },
  { code: 'lk', name: 'Sri Lanka', region: 'Asia', capital: 'Sri Jayawardenepura Kotte', patternTag: 'complex-emblem' },
  { code: 'sy', name: 'Syria', region: 'Asia', capital: 'Damascus', patternTag: 'pan-arab' },
  { code: 'tj', name: 'Tajikistan', region: 'Asia', capital: 'Dushanbe', patternTag: 'complex-emblem' },
  { code: 'th', name: 'Thailand', region: 'Asia', capital: 'Bangkok', patternTag: 'horizontal-tricolor' },
  { code: 'tl', name: 'Timor-Leste', region: 'Asia', capital: 'Dili', patternTag: 'other' },
  { code: 'tr', name: 'Turkey', region: 'Asia', capital: 'Ankara', patternTag: 'star-and-crescent' },
  { code: 'tm', name: 'Turkmenistan', region: 'Asia', capital: 'Ashgabat', patternTag: 'star-and-crescent' },
  { code: 'ae', name: 'United Arab Emirates', region: 'Asia', capital: 'Abu Dhabi', patternTag: 'pan-arab' },
  { code: 'uz', name: 'Uzbekistan', region: 'Asia', capital: 'Tashkent', patternTag: 'star-and-crescent' },
  { code: 'vn', name: 'Vietnam', region: 'Asia', capital: 'Hanoi', patternTag: 'single-color-block' },
  { code: 'ye', name: 'Yemen', region: 'Asia', capital: 'Sanaa', patternTag: 'pan-arab' },
  { code: 'al', name: 'Albania', region: 'Europe', capital: 'Tirana', patternTag: 'single-color-block' },
  { code: 'ad', name: 'Andorra', region: 'Europe', capital: 'Andorra la Vella', patternTag: 'vertical-tricolor' },
  { code: 'at', name: 'Austria', region: 'Europe', capital: 'Vienna', patternTag: 'horizontal-tricolor' },
  { code: 'by', name: 'Belarus', region: 'Europe', capital: 'Minsk', patternTag: 'bicolor' },
  { code: 'be', name: 'Belgium', region: 'Europe', capital: 'Brussels', patternTag: 'vertical-tricolor' },
  { code: 'ba', name: 'Bosnia and Herzegovina', region: 'Europe', capital: 'Sarajevo', patternTag: 'other' },
  { code: 'bg', name: 'Bulgaria', region: 'Europe', capital: 'Sofia', patternTag: 'horizontal-tricolor' },
  { code: 'hr', name: 'Croatia', region: 'Europe', capital: 'Zagreb', patternTag: 'horizontal-tricolor' },
  { code: 'cz', name: 'Czechia', region: 'Europe', capital: 'Prague', patternTag: 'other' },
  { code: 'dk', name: 'Denmark', region: 'Europe', capital: 'Copenhagen', patternTag: 'nordic-cross' },
  { code: 'ee', name: 'Estonia', region: 'Europe', capital: 'Tallinn', patternTag: 'horizontal-tricolor' },
  { code: 'fi', name: 'Finland', region: 'Europe', capital: 'Helsinki', patternTag: 'nordic-cross' },
  { code: 'fr', name: 'France', region: 'Europe', capital: 'Paris', patternTag: 'vertical-tricolor' },
  { code: 'de', name: 'Germany', region: 'Europe', capital: 'Berlin', patternTag: 'horizontal-tricolor' },
  { code: 'gr', name: 'Greece', region: 'Europe', capital: 'Athens', patternTag: 'cross' },
  { code: 'hu', name: 'Hungary', region: 'Europe', capital: 'Budapest', patternTag: 'horizontal-tricolor' },
  { code: 'is', name: 'Iceland', region: 'Europe', capital: 'Reykjavik', patternTag: 'nordic-cross' },
  { code: 'ie', name: 'Ireland', region: 'Europe', capital: 'Dublin', patternTag: 'vertical-tricolor' },
  { code: 'it', name: 'Italy', region: 'Europe', capital: 'Rome', patternTag: 'vertical-tricolor' },
  { code: 'lv', name: 'Latvia', region: 'Europe', capital: 'Riga', patternTag: 'horizontal-tricolor' },
  { code: 'li', name: 'Liechtenstein', region: 'Europe', capital: 'Vaduz', patternTag: 'complex-emblem' },
  { code: 'lt', name: 'Lithuania', region: 'Europe', capital: 'Vilnius', patternTag: 'horizontal-tricolor' },
  { code: 'lu', name: 'Luxembourg', region: 'Europe', capital: 'Luxembourg', patternTag: 'horizontal-tricolor' },
  { code: 'mt', name: 'Malta', region: 'Europe', capital: 'Valletta', patternTag: 'complex-emblem' },
  { code: 'md', name: 'Moldova', region: 'Europe', capital: 'Chisinau', patternTag: 'vertical-tricolor' },
  { code: 'mc', name: 'Monaco', region: 'Europe', capital: 'Monaco', patternTag: 'bicolor' },
  { code: 'me', name: 'Montenegro', region: 'Europe', capital: 'Podgorica', patternTag: 'single-color-block' },
  { code: 'nl', name: 'Netherlands', region: 'Europe', capital: 'Amsterdam', patternTag: 'horizontal-tricolor' },
  { code: 'mk', name: 'North Macedonia', region: 'Europe', capital: 'Skopje', patternTag: 'other' },
  { code: 'no', name: 'Norway', region: 'Europe', capital: 'Oslo', patternTag: 'nordic-cross' },
  { code: 'pl', name: 'Poland', region: 'Europe', capital: 'Warsaw', patternTag: 'bicolor' },
  { code: 'pt', name: 'Portugal', region: 'Europe', capital: 'Lisbon', patternTag: 'complex-emblem' },
  { code: 'ro', name: 'Romania', region: 'Europe', capital: 'Bucharest', patternTag: 'vertical-tricolor' },
  { code: 'ru', name: 'Russia', region: 'Europe', capital: 'Moscow', patternTag: 'horizontal-tricolor' },
  { code: 'sm', name: 'San Marino', region: 'Europe', capital: 'San Marino', patternTag: 'complex-emblem' },
  { code: 'rs', name: 'Serbia', region: 'Europe', capital: 'Belgrade', patternTag: 'horizontal-tricolor' },
  { code: 'sk', name: 'Slovakia', region: 'Europe', capital: 'Bratislava', patternTag: 'horizontal-tricolor' },
  { code: 'si', name: 'Slovenia', region: 'Europe', capital: 'Ljubljana', patternTag: 'horizontal-tricolor' },
  { code: 'es', name: 'Spain', region: 'Europe', capital: 'Madrid', patternTag: 'complex-emblem' },
  { code: 'se', name: 'Sweden', region: 'Europe', capital: 'Stockholm', patternTag: 'nordic-cross' },
  { code: 'ch', name: 'Switzerland', region: 'Europe', capital: 'Bern', patternTag: 'cross' },
  { code: 'ua', name: 'Ukraine', region: 'Europe', capital: 'Kyiv', patternTag: 'bicolor' },
  { code: 'gb', name: 'United Kingdom', region: 'Europe', capital: 'London', patternTag: 'complex-emblem' },
  { code: 'va', name: 'Vatican City', region: 'Europe', capital: 'Vatican City', patternTag: 'complex-emblem' },
  { code: 'ag', name: 'Antigua and Barbuda', region: 'Americas', capital: 'Saint John\'s', patternTag: 'other' },
  { code: 'bs', name: 'Bahamas', region: 'Americas', capital: 'Nassau', patternTag: 'other' },
  { code: 'bb', name: 'Barbados', region: 'Americas', capital: 'Bridgetown', patternTag: 'other' },
  { code: 'bz', name: 'Belize', region: 'Americas', capital: 'Belmopan', patternTag: 'complex-emblem' },
  { code: 'ca', name: 'Canada', region: 'Americas', capital: 'Ottawa', patternTag: 'other' },
  { code: 'cr', name: 'Costa Rica', region: 'Americas', capital: 'San Jose', patternTag: 'horizontal-tricolor' },
  { code: 'cu', name: 'Cuba', region: 'Americas', capital: 'Havana', patternTag: 'other' },
  { code: 'dm', name: 'Dominica', region: 'Americas', capital: 'Roseau', patternTag: 'other' },
  { code: 'do', name: 'Dominican Republic', region: 'Americas', capital: 'Santo Domingo', patternTag: 'complex-emblem' },
  { code: 'sv', name: 'El Salvador', region: 'Americas', capital: 'San Salvador', patternTag: 'complex-emblem' },
  { code: 'gd', name: 'Grenada', region: 'Americas', capital: 'Saint George\'s', patternTag: 'other' },
  { code: 'gt', name: 'Guatemala', region: 'Americas', capital: 'Guatemala City', patternTag: 'complex-emblem' },
  { code: 'ht', name: 'Haiti', region: 'Americas', capital: 'Port-au-Prince', patternTag: 'complex-emblem' },
  { code: 'hn', name: 'Honduras', region: 'Americas', capital: 'Tegucigalpa', patternTag: 'complex-emblem' },
  { code: 'jm', name: 'Jamaica', region: 'Americas', capital: 'Kingston', patternTag: 'saltire' },
  { code: 'mx', name: 'Mexico', region: 'Americas', capital: 'Mexico City', patternTag: 'vertical-tricolor' },
  { code: 'ni', name: 'Nicaragua', region: 'Americas', capital: 'Managua', patternTag: 'complex-emblem' },
  { code: 'pa', name: 'Panama', region: 'Americas', capital: 'Panama City', patternTag: 'other' },
  { code: 'kn', name: 'Saint Kitts and Nevis', region: 'Americas', capital: 'Basseterre', patternTag: 'other' },
  { code: 'lc', name: 'Saint Lucia', region: 'Americas', capital: 'Castries', patternTag: 'other' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines', region: 'Americas', capital: 'Kingstown', patternTag: 'other' },
  { code: 'tt', name: 'Trinidad and Tobago', region: 'Americas', capital: 'Port of Spain', patternTag: 'other' },
  { code: 'us', name: 'United States', region: 'Americas', capital: 'Washington, D.C.', patternTag: 'other' },
  { code: 'ar', name: 'Argentina', region: 'Americas', capital: 'Buenos Aires', patternTag: 'complex-emblem' },
  { code: 'bo', name: 'Bolivia', region: 'Americas', capital: 'Sucre', patternTag: 'horizontal-tricolor' },
  { code: 'br', name: 'Brazil', region: 'Americas', capital: 'Brasilia', patternTag: 'complex-emblem' },
  { code: 'cl', name: 'Chile', region: 'Americas', capital: 'Santiago', patternTag: 'other' },
  { code: 'co', name: 'Colombia', region: 'Americas', capital: 'Bogota', patternTag: 'horizontal-tricolor' },
  { code: 'ec', name: 'Ecuador', region: 'Americas', capital: 'Quito', patternTag: 'complex-emblem' },
  { code: 'gy', name: 'Guyana', region: 'Americas', capital: 'Georgetown', patternTag: 'other' },
  { code: 'py', name: 'Paraguay', region: 'Americas', capital: 'Asuncion', patternTag: 'horizontal-tricolor' },
  { code: 'pe', name: 'Peru', region: 'Americas', capital: 'Lima', patternTag: 'complex-emblem' },
  { code: 'sr', name: 'Suriname', region: 'Americas', capital: 'Paramaribo', patternTag: 'other' },
  { code: 'uy', name: 'Uruguay', region: 'Americas', capital: 'Montevideo', patternTag: 'other' },
  { code: 've', name: 'Venezuela', region: 'Americas', capital: 'Caracas', patternTag: 'complex-emblem' },
  { code: 'au', name: 'Australia', region: 'Oceania', capital: 'Canberra', patternTag: 'complex-emblem' },
  { code: 'fj', name: 'Fiji', region: 'Oceania', capital: 'Suva', patternTag: 'complex-emblem' },
  { code: 'ki', name: 'Kiribati', region: 'Oceania', capital: 'Tarawa', patternTag: 'other' },
  { code: 'mh', name: 'Marshall Islands', region: 'Oceania', capital: 'Majuro', patternTag: 'other' },
  { code: 'fm', name: 'Micronesia', region: 'Oceania', capital: 'Palikir', patternTag: 'other' },
  { code: 'nr', name: 'Nauru', region: 'Oceania', capital: 'Yaren', patternTag: 'other' },
  { code: 'nz', name: 'New Zealand', region: 'Oceania', capital: 'Wellington', patternTag: 'complex-emblem' },
  { code: 'pw', name: 'Palau', region: 'Oceania', capital: 'Ngerulmud', patternTag: 'single-color-block' },
  { code: 'pg', name: 'Papua New Guinea', region: 'Oceania', capital: 'Port Moresby', patternTag: 'complex-emblem' },
  { code: 'ws', name: 'Samoa', region: 'Oceania', capital: 'Apia', patternTag: 'other' },
  { code: 'sb', name: 'Solomon Islands', region: 'Oceania', capital: 'Honiara', patternTag: 'complex-emblem' },
  { code: 'to', name: 'Tonga', region: 'Oceania', capital: 'Nuku\'alofa', patternTag: 'other' },
  { code: 'tv', name: 'Tuvalu', region: 'Oceania', capital: 'Funafuti', patternTag: 'other' },
  { code: 'vu', name: 'Vanuatu', region: 'Oceania', capital: 'Port Vila', patternTag: 'complex-emblem' },
]
