// Curated base-shape library (SPEC §6, §7, §29). Each shape is a connected
// polyomino on a square lattice, generated by exhaustively enumerating fixed
// polyominoes per cell count and filtering to ones that are:
//
//   - not rotationally symmetric at 90/180/270° (so a 90°-rotated copy is
//     never visually identical to the original — required for an
//     unambiguous "which is the same shape, rotated?" trial)
//   - not reflection-equivalent to itself at any rotation (so a mirrored
//     distractor is never accidentally the same as a valid answer)
//   - bounded to a small rendering footprint (≤4×4 for cellCount 4-6, ≤5×5
//     for 7-8, so candidate cards stay readable on a phone screen)
//
// then hand-picking a visually diverse subset. See composables/mentalrotation/
// geometry.js for the validating functions, and geometry.test.js /
// trialGenerator.test.js for the checks re-run against every shape below.
//
// Pool sizes by cellCount (a difficulty's pool is every shape with
// cellCount <= its own max — see constants/mentalrotation/difficulties.js):
//   cellCount<=5 (Easy):      12 shapes
//   cellCount<=6 (Medium):    30 shapes
//   cellCount<=7 (Hard):      44 shapes
//   cellCount<=8 (Very Hard): 58 shapes
//
// Only 2 free (rotation-distinct) shapes exist at cellCount=4 at all — every
// other 4-cell polyomino is either rotationally symmetric (O, S/Z, I) or
// self-reflection-symmetric (T), so Easy's pool also includes cellCount=5 to
// have enough shapes for SPEC §30's recency-exclusion window to work.
export const MENTALROTATION_SHAPES = [
  { id: 's01', cells: [[0,0],[0,1],[0,2],[1,0]], cellCount: 4 },
  { id: 's02', cells: [[0,0],[1,0],[1,1],[1,2]], cellCount: 4 },
  { id: 's03', cells: [[0,0],[0,1],[0,2],[1,0],[1,1]], cellCount: 5 },
  { id: 's04', cells: [[0,0],[0,1],[1,0],[1,1],[1,2]], cellCount: 5 },
  { id: 's05', cells: [[0,0],[0,1],[0,2],[0,3],[1,0]], cellCount: 5 },
  { id: 's06', cells: [[0,0],[0,1],[0,2],[0,3],[1,1]], cellCount: 5 },
  { id: 's07', cells: [[0,0],[0,1],[1,1],[1,2],[1,3]], cellCount: 5 },
  { id: 's08', cells: [[0,0],[1,0],[1,1],[1,2],[1,3]], cellCount: 5 },
  { id: 's09', cells: [[0,1],[0,2],[0,3],[1,0],[1,1]], cellCount: 5 },
  { id: 's10', cells: [[0,1],[1,0],[1,1],[1,2],[1,3]], cellCount: 5 },
  { id: 's11', cells: [[0,0],[1,0],[1,1],[1,2],[2,1]], cellCount: 5 },
  { id: 's12', cells: [[0,1],[1,0],[1,1],[1,2],[2,0]], cellCount: 5 },
  { id: 's13', cells: [[0,0],[0,1],[0,2],[0,3],[1,0],[1,1]], cellCount: 6 },
  { id: 's14', cells: [[0,0],[0,1],[0,2],[0,3],[1,0],[1,2]], cellCount: 6 },
  { id: 's15', cells: [[0,0],[0,1],[1,0],[1,1],[1,2],[1,3]], cellCount: 6 },
  { id: 's16', cells: [[0,1],[0,2],[0,3],[1,0],[1,1],[1,3]], cellCount: 6 },
  { id: 's17', cells: [[0,0],[0,1],[0,2],[1,0],[1,2],[2,2]], cellCount: 6 },
  { id: 's18', cells: [[0,0],[0,1],[1,0],[1,1],[1,2],[2,2]], cellCount: 6 },
  { id: 's19', cells: [[0,0],[1,0],[1,1],[1,2],[2,0],[2,1]], cellCount: 6 },
  { id: 's20', cells: [[0,2],[1,0],[1,1],[1,2],[2,0],[2,1]], cellCount: 6 },
  { id: 's21', cells: [[0,0],[0,1],[0,2],[0,3],[1,1],[2,1]], cellCount: 6 },
  { id: 's22', cells: [[0,0],[0,1],[1,1],[1,2],[1,3],[2,2]], cellCount: 6 },
  { id: 's23', cells: [[0,0],[0,1],[1,1],[1,2],[1,3],[2,3]], cellCount: 6 },
  { id: 's24', cells: [[0,0],[1,0],[1,1],[1,2],[1,3],[2,2]], cellCount: 6 },
  { id: 's25', cells: [[0,0],[1,0],[2,0],[2,1],[2,2],[2,3]], cellCount: 6 },
  { id: 's26', cells: [[0,1],[0,2],[0,3],[1,0],[1,1],[2,1]], cellCount: 6 },
  { id: 's27', cells: [[0,1],[1,0],[1,1],[1,2],[1,3],[2,0]], cellCount: 6 },
  { id: 's28', cells: [[0,1],[1,1],[1,2],[1,3],[2,0],[2,1]], cellCount: 6 },
  { id: 's29', cells: [[0,2],[0,3],[1,0],[1,1],[1,2],[2,0]], cellCount: 6 },
  { id: 's30', cells: [[0,2],[1,1],[1,2],[1,3],[2,0],[2,1]], cellCount: 6 },
  { id: 's31', cells: [[0,0],[0,1],[0,2],[0,3],[1,0],[1,1],[1,2]], cellCount: 7 },
  { id: 's32', cells: [[0,0],[0,1],[0,2],[0,3],[0,4],[1,1],[1,2]], cellCount: 7 },
  { id: 's33', cells: [[0,1],[0,2],[1,0],[1,1],[1,2],[1,3],[1,4]], cellCount: 7 },
  { id: 's34', cells: [[0,0],[0,1],[0,2],[0,3],[1,1],[2,0],[2,1]], cellCount: 7 },
  { id: 's35', cells: [[0,0],[0,1],[1,0],[2,0],[2,1],[2,2],[2,3]], cellCount: 7 },
  { id: 's36', cells: [[0,0],[1,0],[1,1],[1,2],[1,3],[2,0],[2,3]], cellCount: 7 },
  { id: 's37', cells: [[0,1],[0,2],[0,3],[1,0],[1,1],[2,0],[2,1]], cellCount: 7 },
  { id: 's38', cells: [[0,1],[1,0],[1,1],[1,2],[1,3],[2,1],[2,2]], cellCount: 7 },
  { id: 's39', cells: [[0,2],[1,0],[1,1],[1,2],[1,3],[2,0],[2,2]], cellCount: 7 },
  { id: 's40', cells: [[0,0],[0,1],[0,2],[0,3],[0,4],[1,1],[2,1]], cellCount: 7 },
  { id: 's41', cells: [[0,0],[1,0],[1,1],[1,2],[2,2],[2,3],[2,4]], cellCount: 7 },
  { id: 's42', cells: [[0,2],[0,3],[0,4],[1,0],[1,1],[1,2],[2,0]], cellCount: 7 },
  { id: 's43', cells: [[0,0],[1,0],[1,1],[1,2],[1,3],[2,1],[3,1]], cellCount: 7 },
  { id: 's44', cells: [[0,1],[1,1],[1,2],[1,3],[2,0],[2,1],[3,0]], cellCount: 7 },
  { id: 's45', cells: [[0,0],[0,1],[0,2],[0,3],[0,4],[1,0],[1,1],[1,2]], cellCount: 8 },
  { id: 's46', cells: [[0,0],[0,1],[0,2],[1,0],[1,2],[1,3],[2,0],[2,1]], cellCount: 8 },
  { id: 's47', cells: [[0,1],[0,2],[0,3],[1,0],[1,1],[1,3],[2,0],[2,3]], cellCount: 8 },
  { id: 's48', cells: [[0,0],[0,1],[0,2],[0,3],[0,4],[1,0],[1,4],[2,4]], cellCount: 8 },
  { id: 's49', cells: [[0,0],[0,1],[1,0],[1,1],[1,2],[1,3],[1,4],[2,3]], cellCount: 8 },
  { id: 's50', cells: [[0,0],[1,0],[1,1],[1,2],[2,1],[2,2],[2,3],[2,4]], cellCount: 8 },
  { id: 's51', cells: [[0,1],[0,4],[1,0],[1,1],[1,2],[1,3],[1,4],[2,0]], cellCount: 8 },
  { id: 's52', cells: [[0,2],[1,1],[1,2],[1,3],[1,4],[2,0],[2,1],[2,3]], cellCount: 8 },
  { id: 's53', cells: [[0,0],[0,1],[1,0],[2,0],[2,1],[2,2],[2,3],[3,3]], cellCount: 8 },
  { id: 's54', cells: [[0,0],[1,0],[1,2],[2,0],[2,1],[2,2],[2,3],[3,2]], cellCount: 8 },
  { id: 's55', cells: [[0,1],[1,1],[1,2],[1,3],[2,0],[2,1],[2,3],[3,3]], cellCount: 8 },
  { id: 's56', cells: [[0,3],[1,0],[1,1],[1,3],[2,1],[2,2],[2,3],[3,1]], cellCount: 8 },
  { id: 's57', cells: [[0,0],[1,0],[2,0],[2,1],[2,2],[2,3],[2,4],[3,4]], cellCount: 8 },
  { id: 's58', cells: [[0,2],[1,0],[1,1],[1,2],[1,3],[1,4],[2,0],[3,0]], cellCount: 8 },
]
